"""create users devices sessions risk_logs admin_overrides tables

Revision ID: 36277db30bd7
Revises: 0489cc1fe987
Create Date: 2026-10-05 09:19:39.230673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36277db30bd7'
down_revision: Union[str, Sequence[str], None] = '0489cc1fe987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
