"""create users devices sessions risk_logs admin_overrides tables

Revision ID: d2217c2fbd36
Revises: 36277db30bd7
Create Date: 2026-10-05 09:37:22.702996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2217c2fbd36'
down_revision: Union[str, Sequence[str], None] = '36277db30bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_hash', sa.String(length=255), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index('idx_devices_user_hash', 'devices', ['user_id', 'device_hash'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('geolocation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sessions_ip_address'), 'sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('risk_logs',
    sa.Column('risk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('behavior_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('device_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index(op.f('ix_risk_logs_created_at'), 'risk_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_logs_risk_level'), 'risk_logs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_logs_session_id'), 'risk_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_user_id'), 'risk_logs', ['user_id'], unique=False)
    op.create_table('admin_overrides',
    sa.Column('override_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('risk_log_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_taken', sa.String(length=255), nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_log_id'], ['risk_logs.risk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_event_id')
    )
    op.create_index(op.f('ix_admin_overrides_admin_id'), 'admin_overrides', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_overrides_risk_log_id'), 'admin_overrides', ['risk_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_overrides_risk_log_id'), table_name='admin_overrides')
    op.drop_index(op.f('ix_admin_overrides_admin_id'), table_name='admin_overrides')
    op.drop_table('admin_overrides')
    op.drop_index(op.f('ix_risk_logs_user_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_session_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_risk_level'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_created_at'), table_name='risk_logs')
    op.drop_table('risk_logs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ip_address'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index('idx_devices_user_hash', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
